# Generated by Django 6.0.2 on 2026-02-24 15:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='review',
            new_name='reviews_rev_content_8f060c_idx',
            old_name='reviews_ct_obj_status_idx',
        ),
        migrations.AlterField(
            model_name='review',
            name='moderation_note',
            field=models.TextField(blank=True, help_text='Admin-only note explaining moderation action.'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(help_text='1 (poor) to 5 (excellent)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
