# Generated by Django 6.0.2 on 2026-02-24 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_cr2_cr3_promotion_ranking_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='promotionevent',
            new_name='gym_promoti_content_709427_idx',
            old_name='gym_promo_ct_obj_type_idx',
        ),
    ]
