# Generated by Django 6.0.2 on 2026-02-24 15:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gym', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('BOOKED', 'Booked'), ('CANCELLED', 'Cancelled'), ('ATTENDED', 'Attended'), ('MISSED', 'Missed')], default='BOOKED', max_length=12)),
                ('booked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('slot_start', models.DateTimeField(blank=True, null=True)),
                ('slot_end', models.DateTimeField(blank=True, null=True)),
                ('status_changed_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='gym.gymequipment')),
                ('status_changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_changes', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('workout_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='gym.workoutclass')),
            ],
            options={
                'ordering': ['-booked_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'BOOKED')), fields=('user', 'workout_class'), name='unique_active_class_booking'), models.UniqueConstraint(condition=models.Q(('status', 'BOOKED')), fields=('user', 'equipment', 'slot_start'), name='unique_active_equipment_booking')],
            },
        ),
    ]
